### PR TITLE
Fix error message

### PR DESCRIPTION
**Pull request by andreasbeer1981**
Fixed a typo in the URL of the error message that was driving me crazy

### CODE REVIEW

**Comment by neonichu** [comment]
Cool, thanks for the contribution!

**Comment by pxlpnk** [comment]
@neonichu could you please update the changelog? (:

**Comment by neonichu** [comment]
Added to the changelog in c0a662cfc936593553841425198864f9d1254f4f

**Comment by pxlpnk** [comment]
Thank you!

**Pull request merged**
