### PR TITLE
Parse nested locales in `AssetFields`

### LINKED ISSUE #63: Asset `file` properties are nil when using sync
An asset retrieved via sync looks like this:

```ruby
#<Contentful::Asset: @fields={:title=>"{\"en-US\"=>\"Doge\"}", :file=>#<Contentful::File: @properties={:fileName=>nil, :contentType=>nil, :details=>nil, :url=>nil}>, :description=>"{\"en-US\"=>\"nice picture\"}"} @sys={:space=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"Space", :id=>"cfexampleapi"}>, :type=>"Asset", :id=>"1x0xpXu4pSGS4OukSyWGUK", :revision=>6, :createdAt=>#<DateTime: 2013-11-06T09:45:10+00:00 ((2456603j,35110s,0n),+0s,2299161j)>, :updatedAt=>#<DateTime: 2013-12-18T13:27:14+00:00 ((2456645j,48434s,917000000n),+0s,2299161j)>}>
```

Obviously, the file properties should not be `nil`.

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #63

### CODE REVIEW

**Comment by neonichu** [comment]
I have simply copied the magic from `Contentful::Resource::Fields` so that assets work the same way. I didn't fully understand why the split between the two was made, would obviously be nicer if both code paths would simply share this functionality.

**Comment by pxlpnk** [comment]
Suggestion:
We pull this: https://github.com/contentful/contentful.rb/blob/5ee811d4c7d4c94272e3e84a384d237ab106973f/lib/contentful/resource/fields.rb#L28-L43
into the `resource.rb` module and make it available on the `fields.rb` and `assets_fields.rb` modules?
With this we can avoid code duplication as that code on its own is already rather complex.

**Comment by neonichu** [comment]
@pxlpnk sounds good, will update the PR

**Comment by pxlpnk** [comment]
Looks good!

**Pull request merged**
